### ISSUE TITLE
Files not found in Box

### ISSUE THREAD

**Issue by ngc-shj** [VITA-Group/WeLore#1]
Thank you for the great job.

I followed the installation instructions in REAMDE, but I couldn't find any files in the links to Box shown in Steps 4 and 5. Is it possible to make these files public?

**Comment by Ajay1994** [comment]
Thanks for your interest. We will release all the files on https://huggingface.co/vita-group by this week.

Updated the file here: https://huggingface.co/vita-group/svd-checkpoints
